import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { notFound } from "next/navigation";
import FloatingActions from "../../components/FloatingActions";
import SiteFooter from "../../components/SiteFooter";
import SiteHeader from "../../components/SiteHeader";

const articles = {
  "deen-dayal-jan-awas-yojna": {
    category: "Housing policy", title: "What is Deen Dayal Jan Awas Yojna?", image: "/assets/news/ddjay.jpeg", read: "6 min read",
    intro: "A home is more than just walls and a roof—it's your comfort zone, your happy place, and your biggest asset. But for many people, especially middle-class families, buying a home can feel out of reach. That's where the Deen Dayal Jan Awas Yojna (DDJAY) comes in.",
    sections: [
      { heading: "What Is the Deen Dayal Jan Awas Yojna?", paragraphs: ["Deen Dayal Jan Awas Yojna (or DDJAY for short) is an affordable plot scheme that helps people buy small residential plots—between 60 and 180 square yards—in growing towns of Haryana like Jhajjar, Rohtak, Sohna, Gurugram, Faridabad, Karnal and more. Instead of building huge apartment towers, the government allows private developers to create small gated colonies with all basic services like roads, water, sewer lines, parks, and lighting.", "You can buy a plot in one of these colonies, get a home loan, and build a house at your own pace."], points: [] },
      { heading: "Why This Scheme Was Started", paragraphs: ["Land in big cities has become too expensive for most families. Plus, illegal colonies are growing fast, causing safety and legal problems for homebuyers. To solve this, the Haryana Government created DDJAY. It encourages development in low- and medium-potential towns, where land is still affordable. The goal is simple—legal, affordable, and planned homeownership for the common man."], points: [] },
      { heading: "Where Can You Buy These Plots?", paragraphs: ["These places are connected to big roads, schools, hospitals, and public transport—making them great for living or investing."], points: ["Jhajjar (Sectors 11, 27, 36)", "Rohtak (Sectors 25D, 35, 37)", "Sohna (Gurugram region)", "Faridabad, Palwal, Yamunanagar, and others"] },
      { heading: "Example Project: South City 1, Jhajjar", paragraphs: ["One of the most trusted DDJAY projects is South City 1, located in Sector 36, Jhajjar. It is developed by M/s Vedmaan Group and is fully approved by RERA (Reg. No. HRERA-PKL-JJR-572-2024). The project offers legal residential plots starting from 107 square yards. South City 1 comes with wide roads, electricity, water connections, sewerage, green parks, and even space for shops. It's a gated community where you can build your dream home in a safe and peaceful setting."], points: [] },
      { heading: "Who Can Apply?", paragraphs: [], points: ["People who live in Haryana", "People who do not own a pucca house anywhere in India", "Families from EWS, LIG, or MIG income groups", "First-time buyers who have not benefited from other housing schemes"] },
      { heading: "What's the Cost and How Do You Pay?", paragraphs: ["Plots under DDJAY usually cost between ₹43,000 to ₹48,000 per square yard depending on the location. Booking starts with a registration amount of ₹11,000 or ₹31,000, which is usually refundable if not allotted. The rest of the payment is done in easy stages. Once the full payment is made, you get the registry in your name and can start construction."], points: [] },
      { heading: "Home Loan and Government Subsidy Support", paragraphs: ["Many people worry about how to finance their home. Don't worry—banks like SBI, HDFC, PNB, and others offer home loans and plot loans for DDJAY projects. If you are eligible, you can also get up to ₹2.67 lakh subsidy through the PMAY CLSS scheme, which reduces your EMI. This makes the dream of owning and building a home even easier."], points: [] },
      { heading: "Why DDJAY Is a Great Choice", paragraphs: [], points: ["You get legal, freehold property", "You can build your house when you're ready", "You get all basic infrastructure already in place", "You save money with PMAY subsidy and loan options", "Your investment grows in value as the town develops"] },
      { heading: "Final Words", paragraphs: ["The Deen Dayal Jan Awas Yojna is not just a housing policy—it's a real opportunity for regular families to build a better life. With legal safety, affordable pricing, and growing townships, it's one of the best ways to own land in Haryana today. If you're thinking about buying a plot in Jhajjar, Rohtak, Sohna, or any nearby town, we're here to help. Our team can guide you with project details, site visits, document help, loan assistance, and more.", "Reach out today and take the first step toward owning your own home."], points: [] },
    ],
  },
  "haryana-film-city": {
    category: "Regional development", title: "Haryana Film City – India’s New Cinema Destination in the Making", image: "/assets/news/haryana-film-city.jpeg", read: "5 min read",
    intro: "The Indian film industry is one of the largest in the world, and now Haryana is stepping onto the stage in a big way. The Haryana Government has announced the development of a state-of-the-art Film City in the scenic region of Pinjore, near Panchkula.",
    sections: [
      { heading: "A Big Step for Haryana and Indian Cinema", paragraphs: ["This new project is set to become a creative and commercial hub for filmmakers, artists, and businesses from across the country.", "Whether you're a movie lover, an investor, or just excited about Haryana's growth, here's everything you need to know about the upcoming Haryana Film City."], points: [] },
      { heading: "Where Is the Haryana Film City Being Built?", paragraphs: ["The Haryana Film City will be developed in Pinjore, a beautiful and peaceful town near Panchkula and Chandigarh. Located at the foothills of the Shivalik Hills, Pinjore is known for its natural beauty, open land, and historical charm—making it a perfect location for film shoots and cultural activities.", "The selected land covers nearly 100 to 200 acres, and the area offers excellent road and rail connectivity. Its proximity to Chandigarh also ensures access to airports, studios, and other major infrastructure."], points: [] },
      { heading: "What Will Haryana Film City Include?", paragraphs: ["The Haryana Film City isn't just about shooting movies. It's planned as a complete ecosystem for the film and entertainment industry. Here's what's expected to be included:", "This means the Film City will not only attract filmmakers—but also tourists, students, and cinema lovers."], points: ["Film shooting zones with sets, open spaces, and natural backdrops", "Post-production studios for editing, dubbing, VFX, and sound", "Film schools and training institutes for acting, direction, and film technology", "Office spaces for production houses and media companies", "Film museum and cultural centre to promote regional and Indian cinema", "Tourism zones with cafes, theatres, and shopping areas for visitors"] },
      { heading: "Why Is Haryana Building a Film City?", paragraphs: ["Haryana has always been rich in culture, art, and talent. Many Haryanvi actors, musicians, and storytellers are already making their mark in Bollywood and regional cinema. By building its own Film City, the state wants to give this talent a proper platform—and reduce the film industry's over-dependence on Mumbai and Hyderabad.", "This project will also help:"], points: ["Generate employment for local youth in acting, editing, set design, and more", "Promote Haryanvi language and culture through regional films", "Boost tourism in North Haryana and nearby Himachal/Chandigarh", "Create investment opportunities for media and real estate companies"] },
      { heading: "What It Means for Real Estate and Business", paragraphs: ["The announcement of the Film City has already started increasing the demand for land, residential plots, commercial properties, and studio space in and around Pinjore, Panchkula, and Kalka.", "Real estate investors are showing strong interest in nearby areas, expecting future growth as the Film City becomes operational. It will also open up space for hotels, cafés, rental homes, equipment rentals, training centres, and more."], points: [] },
      { heading: "Government's Role and Future Plans", paragraphs: ["The Haryana Government, led by the Haryana State Industrial and Infrastructure Development Corporation (HSIIDC), is planning this project carefully to ensure it matches international standards. They will be inviting private players and industry experts to build, operate, and manage different parts of the Film City through PPP (Public-Private Partnership) models.", "There are also talks of tax incentives, subsidies, and fast-track approvals for companies who want to set up film-related infrastructure here."], points: [] },
      { heading: "Final Thoughts", paragraphs: ["The Haryana Film City in Pinjore is more than just a film project—it's a bold step toward cultural pride, economic growth, and creative freedom. Whether you're an artist, a business owner, a local resident, or an investor, this is a chance to be part of something visionary.", "Stay tuned as Haryana turns the spotlight toward cinema—and opens the doors to a brand-new creative world."], points: [] },
    ],
  },
  "haryana-government-plot-schemes-2025": {
    category: "Government schemes", title: "Haryana Government Plot Schemes 2025 – Apply for Legal Residential Plots in Prime Towns", image: "/assets/news/haryana-plot-schemes.jpeg", read: "7 min read",
    intro: "If you've been Googling “Haryana government plot scheme 2025”, “HUDA plot application form”, “HSVP plot draw date”, or “affordable plots in Haryana 2025”, you're not alone. Thousands of people are actively looking for safe and legal ways to own land in Haryana through government-approved channels.",
    sections: [
      { heading: "Searching for Government Plots in Haryana?", paragraphs: ["To help you out, here's a complete guide to the top residential plot schemes by the Haryana Government in 2025—including HUDA, HSVP, Panchkula Extension, Karnal sectors, and more."], points: [] },
      { heading: "1. HSVP Plot Scheme 2025 (formerly HUDA)", paragraphs: ["The Haryana Shahari Vikas Pradhikaran (HSVP), earlier known as HUDA, is offering residential plots in prime sectors of cities like Panchkula, Karnal, Kurukshetra, Faridabad, Gurugram, Rohtak, and more.", "Trending sectors in 2025 include Sector 5 and 20 in Panchkula Extension, Sector 28 in Rohtak, and Sector 9 in Karnal. These areas are in high demand due to location, legal safety, and investment value."], points: ["Plot sizes: 90 to 500 square yards", "Application through online draw system", "Transparent allotment process", "Prices starting from ₹30,000/sq. yd onwards", "Possession after 25–30% initial payment"] },
      { heading: "2. Housing Board Haryana Plot Scheme", paragraphs: ["The Housing Board of Haryana offers affordable housing plots and ready-built homes to economically weaker sections (EWS), lower income groups (LIG), and sometimes middle-income groups (MIG).", "In 2025, the board has re-launched schemes for Bhiwani, Yamunanagar, Bahadurgarh, Rewari, and Kaithal. Applications are mostly accepted online through the Housing Board portal and are targeted at salaried people, widows, and senior citizens."], points: [] },
      { heading: "3. Industrial & Commercial Plot Schemes (HSIIDC)", paragraphs: ["Not just for homes—Haryana also offers industrial and commercial plots through HSIIDC (Haryana State Industrial & Infrastructure Development Corporation).", "Top areas in 2025 include IMT Sohna, Kundli, Bawal, and Faridabad Industrial Cluster."], points: [] },
      { heading: "Why These Schemes Are So Popular in 2025", paragraphs: [], points: ["Allotment through lottery/draw – 100% fair process", "Registry and freehold ownership = legal and safe investment", "Subsidy and loan support for eligible categories", "Best cities in Haryana for both living and resale value", "Online application portals = no middlemen, no fraud"] },
      { heading: "Want to Apply for a Haryana Plot in 2025?", paragraphs: ["You can apply online on the official HSVP, Housing Board Haryana, HSIIDC and Haryana e-procurement portals.", "Or, you can reach out to verified real estate consultants like us to get the latest updates, assistance in filling the forms, and guidance on project visits and loan processing."], points: ["https://www.hsvphry.org.in/", "https://hbh.gov.in/", "https://hsiidc.org.in/", "https://www.haryanaeprocurement.gov.in/"] },
      { heading: "Final Words – Let's Help You Get the Right Plot", paragraphs: ["Every month, thousands of people search for HUDA plots 2025 online form, HSVP residential plot scheme draw, Haryana EWS plot scheme 2025, and industrial plots in IMT Faridabad.", "We stay updated with every new plot scheme, draw result, and location-specific opportunity in Haryana. Whether you want to live, build, or invest, let us help you secure a legal plot in a growing township—backed by the Haryana government."], points: [] },
    ],
  },
} as const;

type ArticleSlug = keyof typeof articles;
export function generateStaticParams() { return Object.keys(articles).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = articles[slug as ArticleSlug]; return article ? { title: `${article.title} | Vedmaan Group`, description: article.intro } : {}; }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const article = articles[slug as ArticleSlug]; if (!article) notFound();
  const related = Object.entries(articles).filter(([key]) => key !== slug).slice(0, 2);
  return <main className="articlePage"><SiteHeader />
    <section className="articleHero articleTextHero"><div className="articleHeroShade" /><div className="articleHeroCopy"><Link href="/news"><i><ArrowLeft /></i> Back to News</Link><p>{article.category}</p><h1>{article.title}</h1><strong>{article.intro}</strong></div></section>
    <section className="articleLayout"><article className="articleBody"><div className="articleBodyCover"><Image src={article.image} alt={article.title} fill priority sizes="(max-width: 900px) 86vw, 780px" /></div><p className="articleLead">{article.intro}</p>{article.sections.map((section, index) => <section id={`section-${index + 1}`} key={section.heading}><small>{String(index + 1).padStart(2, "0")}</small><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.points.length > 0 && <ul>{section.points.map((point) => <li key={point}>{point}</li>)}</ul>}</section>)}</article>
      <aside className="articleAside">
        <div className="articleIndex"><div className="articleSidebarVisual"><Image src="/assets/news/article-sidebar-planning.png" alt="A residential site plan, architectural model and planning compass" fill sizes="(max-width: 900px) 86vw, 360px" /></div><div className="articleIndexContent"><small>In this article</small><h3>Explore the key points.</h3><nav>{article.sections.map((section, index) => <a href={`#section-${index + 1}`} key={section.heading}><i>0{index + 1}</i><span>{section.heading}</span><ArrowRight /></a>)}</nav></div></div>
        <div className="articleAsideCta"><small>Planning a visit?</small><h3>Understand the location in person.</h3><p>Speak with our team for current project information and a guided visit.</p><Link className="button gold" href="/contact#enquiry">Contact our team <ArrowRight /></Link></div>
      </aside>
    </section>
    <section className="articleRelated"><p className="eyebrow"><span /> Continue reading</p><h2>More from<br /><em>News & Updates.</em></h2><div>{related.map(([key, item]) => <Link href={`/news/${key}`} key={key}><span><Image src={item.image} alt="" fill sizes="(max-width:700px) 100vw, 40vw" /></span><small>{item.category}</small><h3>{item.title}</h3><p>{item.intro}</p><b>Read article <ArrowRight /></b></Link>)}</div></section>
    <FloatingActions /><SiteFooter />
  </main>;
}
