import type { Metadata } from "next";
import LegalPage from "../components/LegalPage";

export const metadata: Metadata = { title: "Privacy Policy | Vedmaan Group", description: "Vedmaan Group privacy policy for website visitors and enquiries." };

export default function PrivacyPolicyPage() {
  return <LegalPage eyebrow="Legal" title="Privacy Policy" intro="This policy explains how information submitted through the Vedmaan Group website may be collected and used." sections={[
    { title: "Information you provide", body: ["We may collect the information you enter in our contact, site-visit or agent-registration forms, including your name, phone number, email address, message, company details, office address and RERA registration number.", "We also receive the project or service preferences you choose, the page from which an enquiry was submitted and any consent selections made with the form. Please provide only information that is accurate and relevant to your request."] },
    { title: "How information may be used", body: ["Information may be used to respond to enquiries, arrange site visits, review agent registrations, share requested project information and communicate relevant products, services, promotions or offers where consent has been provided.", "It may also be used to maintain enquiry records, improve our response process, prevent misuse of website forms and meet applicable business, legal or regulatory requirements."] },
    { title: "Communication and consent", body: ["When you submit an enquiry and provide consent, Vedmaan Group or its authorised representatives may contact you by telephone, SMS, email or WhatsApp regarding your request and relevant offerings.", "You may ask us to stop promotional communication at any time. Service-related communication needed to answer an active enquiry or arrange a requested visit may still be sent."] },
    { title: "Sharing and protection", body: ["Information may be made available to authorised employees, representatives or service providers where needed to handle your request, operate the website or support our communication systems. We do not intend to make submitted personal information publicly available.", "We take reasonable administrative and technical measures to protect information, but no online transmission or storage method can be guaranteed as completely secure."] },
    { title: "Data retention", body: ["Enquiry and registration details may be retained for as long as reasonably necessary to respond to the request, maintain business records, resolve concerns and comply with applicable obligations.", "Information that is no longer required may be deleted, anonymised or retained where a longer period is required by law or for legitimate record-keeping purposes."] },
    { title: "Your choices", body: ["You may contact us to request correction of inaccurate details, ask a question about submitted information or withdraw consent for promotional communication. We may need to verify the request before acting on it."] },
    { title: "Cookies and technical data", body: ["The website and its hosting or analytics services may process limited technical information such as browser type, device information, IP address and page activity for security, performance and basic usage analysis."] },
    { title: "Third-party services", body: ["This website may use or link to third-party services, including maps, messaging platforms and external websites. Their own terms and privacy practices apply when you choose to use those services."] },
    { title: "Contact", body: ["For questions about this policy or information submitted through the website, contact Vedmaan Group at info@vedmaangroup.com or call +91 83839 53751."] },
  ]} />;
}
